In [1]:
"""
PYTHON ARRAYS (USING LISTS) - COMPLETE DSA CHEAT SHEET
"""
# 1. CREATION
arr = [10, 20, 30, 40, 50]
empty = []
zeros = [0] * 5
mixed = [1, "Python", 3.14, True]

print("Original:", arr)

# 2. ACCESSING ELEMENTS
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Second last:", arr[-2])

# 3. TRAVERSAL
print("\nTraversal using for loop:")
for x in arr:
    print(x, end=" ")

print("\nTraversal using index:")
for i in range(len(arr)):
    print(f"Index {i}: {arr[i]}")

# 4. INSERTION
arr.append(60)                 # End insertion
arr.insert(2, 25)              # Insert at index
arr.extend([70, 80])           # Add multiple elements
print("\nAfter insertion:", arr)

# 5. DELETION
arr.remove(25)                 # Remove first occurrence
last = arr.pop()               # Remove last element
middle = arr.pop(2)            # Remove by index
del arr[0]                     # Delete by index
# del arr[1:3]                 # Delete range
print("After deletion:", arr)
print("Popped last:", last)
print("Popped middle:", middle)

# 6. SEARCHING
print("\n20 exists?", 20 in arr)
print("Index of 40:", arr.index(40))
print("Count of 20:", arr.count(20))

# Linear Search
key = 50
found = False
for i in range(len(arr)):
    if arr[i] == key:
        print(f"{key} found at index {i}")
        found = True
        break
if not found:
    print(f"{key} not found")

# 7. UPDATe
arr[1] = 99
print("\nAfter update:", arr)

# 8. SLICING
nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print("\nOriginal nums:", nums)
print("nums[2:6]:", nums[2:6])
print("nums[:5]:", nums[:5])
print("nums[5:]:", nums[5:])
print("nums[::-1]:", nums[::-1])
print("nums[::2]:", nums[::2])

# 9. SORTING
a = [5, 2, 8, 1, 9]
print("\nBefore sorting:", a)
a.sort()                       # Ascending
print("Ascending:", a)
a.sort(reverse=True)           # Descending
print("Descending:", a)
print("Sorted copy:", sorted(a))

# 10. REVERSING
a.reverse()
print("\nReversed:", a)

# 11. COPYING
b = a.copy()
c = a[:]
d = list(a)
print("\nCopied array:", b)

# 12. CONCATENATION
x = [1, 2, 3]
y = [4, 5, 6]
z = x + y
print("\nConcatenated:", z)

# 13. COMMON BUILT-IN FUNCTIONS
arr2 = [4, 7, 1, 9, 3]
print("\nLength:", len(arr2))
print("Sum:", sum(arr2))
print("Min:", min(arr2))
print("Max:", max(arr2))
print("Any:", any(arr2))
print("All:", all(arr2))

# 14. ITERATION HELPERS
print("\nEnumerate:")
for index, value in enumerate(arr2):
    print(index, value)

print("\nZip:")
names = ["A", "B", "C"]
scores = [90, 85, 95]
for name, score in zip(names, scores):
    print(name, score)

# 15. LIST COMPREHENSION
squares = [x * x for x in range(10)]
evens = [x for x in range(20) if x % 2 == 0]
print("\nSquares:", squares)
print("Evens:", evens)

# 16. 2D ARRAY
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("\n2D Array:")
for row in matrix:
    print(row)

print("Element at [1][2]:", matrix[1][2])

# 17. STACK OPERATIONS USING ARRAY
stack = []
stack.append(10)
stack.append(20)
stack.append(30)
print("\nStack:", stack)
print("Pop:", stack.pop())
print("Top:", stack[-1])

# 18. QUEUE OPERATIONS (Simple)
from collections import deque
queue = deque()
queue.append(10)
queue.append(20)
queue.append(30)
print("\nQueue:", list(queue))
print("Dequeued:", queue.popleft())
print("Front:", queue[0])

# 19. FREQUENCY COUNT
from collections import Counter
freq = Counter([1, 2, 2, 3, 3, 3, 4])
print("\nFrequency:", freq)

# 20. IMPORTANT DSA PATTERNS
arr3 = [1, 2, 3, 4, 5]

# Prefix Sum
prefix = [0] * len(arr3)
prefix[0] = arr3[0]
for i in range(1, len(arr3)):
    prefix[i] = prefix[i - 1] + arr3[i]
print("\nPrefix Sum:", prefix)

# Two Pointers - Reverse Array
left, right = 0, len(arr3) - 1
while left < right:
    arr3[left], arr3[right] = arr3[right], arr3[left]
    left += 1
    right -= 1
print("Reversed using two pointers:", arr3)

# Sliding Window (Maximum sum of size k)
arr4 = [2, 1, 5, 1, 3, 2]
k = 3
window_sum = sum(arr4[:k])
max_sum = window_sum
for i in range(k, len(arr4)):
    window_sum += arr4[i] - arr4[i - k]
    max_sum = max(max_sum, window_sum)
print("Maximum window sum:", max_sum)

# 21. TIME COMPLEXITIES
"""
Access by index      : O(1)
Append               : O(1) amortized
Insert/Delete at end : O(1)
Insert/Delete middle : O(n)
Search               : O(n)
Sort                 : O(n log n)
Reverse              : O(n)
Slice                : O(k)
"""


Original: [10, 20, 30, 40, 50]
First element: 10
Last element: 50
Second last: 40

Traversal using for loop:
10 20 30 40 50 
Traversal using index:
Index 0: 10
Index 1: 20
Index 2: 30
Index 3: 40
Index 4: 50

After insertion: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After deletion: [20, 40, 50, 60, 70]
Popped last: 80
Popped middle: 30

20 exists? True
Index of 40: 1
Count of 20: 1
50 found at index 2

After update: [20, 99, 50, 60, 70]

Original nums: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
nums[2:6]: [2, 3, 4, 5]
nums[:5]: [0, 1, 2, 3, 4]
nums[5:]: [5, 6, 7, 8, 9]
nums[::-1]: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
nums[::2]: [0, 2, 4, 6, 8]

Before sorting: [5, 2, 8, 1, 9]
Ascending: [1, 2, 5, 8, 9]
Descending: [9, 8, 5, 2, 1]
Sorted copy: [1, 2, 5, 8, 9]

Reversed: [1, 2, 5, 8, 9]

Copied array: [1, 2, 5, 8, 9]

Concatenated: [1, 2, 3, 4, 5, 6]

Length: 5
Sum: 24
Min: 1
Max: 9
Any: True
All: True

Enumerate:
0 4
1 7
2 1
3 9
4 3

Zip:
A 90
B 85
C 95

Squares: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Evens: [

'\nAccess by index      : O(1)\nAppend               : O(1) amortized\nInsert/Delete at end : O(1)\nInsert/Delete middle : O(n)\nSearch               : O(n)\nSort                 : O(n log n)\nReverse              : O(n)\nSlice                : O(k)\n'

In [2]:
import array
val = array.array('i', [1, 2, 3, 45, 5])

for i in range(0, len(val)):
    print(i, val[i])

0 1
1 2
2 3
3 45
4 5


In [3]:
for i in range(0, 5):
    print(val[i], end=" ")
print()
for x in val:
    print(x, end=", ")

1 2 3 45 5 
1, 2, 3, 45, 5, 

In [4]:
val2 = [23 ,34 ,45, 67, 78,55.55]
print(type(val2))
for i in range(len(val2)):
    print(val2[i], end=" ")

<class 'list'>
23 34 45 67 78 55.55 

In [5]:
from array import *
val2 = array('d', [23 ,34 ,45, 67, 78,55.55])
print(val2)
print(type(val2))
for i in range(len(val2)):
    print(val2[i], end=" ")

array('d', [23.0, 34.0, 45.0, 67.0, 78.0, 55.55])
<class 'array.array'>
23.0 34.0 45.0 67.0 78.0 55.55 

In [6]:
from array import *
val2 = array('f', [23 ,34 ,45, 67, 78,55.55])
print(val2)
print(type(val2))
for i in range(len(val2)):
    print(val2[i], end=" ")

array('f', [23.0, 34.0, 45.0, 67.0, 78.0, 55.54999923706055])
<class 'array.array'>
23.0 34.0 45.0 67.0 78.0 55.54999923706055 

In [7]:
val3 = array('u', ['a', 'b', 'c', 'd', 'e', 'f'])
print(val3)


array('u', 'abcdef')


C:\Users\mahes\AppData\Local\Temp\ipykernel_14828\1505143137.py:1: DeprecationWarning: The 'u' type code is deprecated and will be removed in Python 3.16
  val3 = array('u', ['a', 'b', 'c', 'd', 'e', 'f'])


In [8]:
print(val2.typecode)
print(val3.typecode)
print(val.typecode)

f
u
i


In [9]:
from array import *

val4 = array('i', [81, 82, 83, 84, 85, 86, 87, 88])
print(val4)

val4.reverse()
for i in range(len(val4)):
    print(val4[i], end=" ")

print()  # move to next line

val4.insert(1, 50)
val4.append(999)
print(val4)

val4[2] = 777
print(val4)

array('i', [81, 82, 83, 84, 85, 86, 87, 88])
88 87 86 85 84 83 82 81 
array('i', [88, 50, 87, 86, 85, 84, 83, 82, 81, 999])
array('i', [88, 50, 777, 86, 85, 84, 83, 82, 81, 999])


In [10]:
copy_arr = array(val4.typecode, (x*2 for x in val4))
print(copy_arr)

for i in range(0, len(copy_arr)):
    print(val4[i], end=", ")


array('i', [176, 100, 1554, 172, 170, 168, 166, 164, 162, 1998])
88, 50, 777, 86, 85, 84, 83, 82, 81, 999, 

In [11]:
print(copy_arr)
copy_arr.pop()
print(copy_arr)
copy_arr.pop()
print(copy_arr)
copy_arr.remove(100)
print(copy_arr)

array('i', [176, 100, 1554, 172, 170, 168, 166, 164, 162, 1998])
array('i', [176, 100, 1554, 172, 170, 168, 166, 164, 162])
array('i', [176, 100, 1554, 172, 170, 168, 166, 164])
array('i', [176, 1554, 172, 170, 168, 166, 164])


In [12]:
print(copy_arr)

array('i', [176, 1554, 172, 170, 168, 166, 164])


In [13]:
print(val4)
val5 = val4[2:5]
print(val5)
val6 = val4[::-1]
print("THe reverse of array: ", val6)

array('i', [88, 50, 777, 86, 85, 84, 83, 82, 81, 999])
array('i', [777, 86, 85])
THe reverse of array:  array('i', [999, 81, 82, 83, 84, 85, 86, 777, 50, 88])


In [14]:
# val = array('i', [])
# n = int(input("Enter the no: "))
#
# for i in range(n):
#     val.append(int(input('Enter the elements of array: ')))
#
# print(val)

In [15]:
quant_arr = array('i', [23, 2, 234, 345])
print(quant_arr)

i = quant_arr.index(345)
print(i)

array('i', [23, 2, 234, 345])
3


In [16]:
# from array import *
#
# arr = array('i', [])
# n = int(input("Enter the number: "))
#
# for i in range(n):
#     arr.append(int(input("Enter the input: ")))
#
# for x in arr:
#     print(x, end=" ")

In [17]:
import numpy as np

val = np.array([1, 2, 3])

for x in val:
    print(x, end=" ")

1 2 3 

In [18]:
arr2 = [12, 34, 342, 123]
print(arr2)
print(type(arr2))


[12, 34, 342, 123]
<class 'list'>


In [19]:
arr3 = [9, 80, 78,67, 34]
left, right = 0, len(arr3) -1
while left < right:
    print(arr3[left], arr3[right])
    left +=1
    right -= 1

9 34
80 67


In [20]:
import numpy as np
even_arr = np.array([65, 23, 22, 21, 62])
print(even_arr)

for x in even_arr:
    print(x, end=' ')

[65 23 22 21 62]
65 23 22 21 62 

In [21]:
# numpy give to ability to store the heterogeneous array.

In [22]:
from array import array

newarr = array('f', [1, 2, 4])
print(newarr)
for x in newarr:
    print(x, end=" ")


array('f', [1.0, 2.0, 4.0])
1.0 2.0 4.0 

In [23]:
from numpy import *

new_x1 = linspace(2 ,10, 4)
new_x2 = arange(2 ,10, 4)
new_x2 = logspace(10 ,20, 2)
new_x3 = zeros(7)
new_x4 = ones(9)
print(new_x1)
print(new_x2)
print()
print(new_x3)
print(new_x4)

[ 2.          4.66666667  7.33333333 10.        ]
[1.e+10 1.e+20]

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [24]:
new_x5 = full(10, 55)
print(new_x5)

[55 55 55 55 55 55 55 55 55 55]


In [25]:
one = array([23, 345, 567, 32.23, -1])
print(one)
two = array([[12, 22], [45, 23], [67, 32]])
print(two)

[ 23.   345.   567.    32.23  -1.  ]
[[12 22]
 [45 23]
 [67 32]]


In [26]:
# 3d array
three = array([[[1, 2], [3, 4]],[[1, 2], [3, 4]]])
print(three)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [27]:
arr74 = array([
    [[12, 23, 34],[67, 45, 0]],
    [[12, 23, 34],[67, 45, 0]]
])
print(arr74)
print(type(arr74))
print()

for i in range(len(arr74)):
    print(f"Layer {i}: ")
    for row in arr74[i]:
        print(row)
    print()


[[[12 23 34]
  [67 45  0]]

 [[12 23 34]
  [67 45  0]]]
<class 'numpy.ndarray'>

Layer 0: 
[12 23 34]
[67 45  0]

Layer 1: 
[12 23 34]
[67 45  0]



In [28]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### ARRAY IN DSA Basics


In [29]:
import numpy as np

In [30]:
#the 1d array
arr11 = np.array([1, 2, 34, 45, 78])
print(arr11)
print(type(arr11))
print()

#creating the 2D array
arr12 = np.array([[23, 56], [90,78]])
print(arr12)
print()

#creating the array of 0s
zeors = np.zeros(9)
print(zeors)

[ 1  2 34 45 78]
<class 'numpy.ndarray'>

[[23 56]
 [90 78]]

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
#creating the array of 1s
ones = np.ones(9)
print(ones)
print()

#identity matrix
identity = np.eye(3)
print(identity)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
#range of array
arr13 = np.arange(1, 11, 2)
print(arr13)
arr14 = np.arange(3, 30, 3)
print(f"the Array is: \n{arr14}")

[1 3 5 7 9]
the Array is: 
[ 3  6  9 12 15 18 21 24 27]


In [33]:
#Use of linspace function
# used for to create an array of evently spaces numbers over a specified interval.
arr15 = np.linspace(0, 1, 5)
print(arr15)

arr16 = np.linspace(1, 30, 3)
arr17 = np.linspace(1, 30, 10)
arr18 = np.linspace(1, 30, 30)
print(arr16)
print(arr17)
print(arr18)

[0.   0.25 0.5  0.75 1.  ]
[ 1.  15.5 30. ]
[ 1.          4.22222222  7.44444444 10.66666667 13.88888889 17.11111111
 20.33333333 23.55555556 26.77777778 30.        ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]


In [34]:
arr_new = np.array([{23,45, 67, 23}])
arr_new1 = np.array([23,45, 67, 23])
print(arr_new)
print(arr_new1)
print(arr_new1.size)
print(arr_new1.ndim)

[{67, 45, 23}]
[23 45 67 23]
4
1


In [35]:
# Array attributes
arr19 = np.array([[90, 78, 60],[20, 78, 123], [78, 963, 22]])
print(arr19)
print(arr19.ndim)
print(arr19.shape)
print(arr19.size)
print(arr19.dtype)
print(arr19.itemsize)

[[ 90  78  60]
 [ 20  78 123]
 [ 78 963  22]]
2
(3, 3)
9
int64
8


In [36]:
# Accessing the elements of array
mat = np.array([[1, 2, 4],
               [89, 23, 0],
               [45 ,90, 221]])
print(mat)
print(type(mat))

#IT conuted the diamension from the 0,0 to 2,2 for 3x3 matrix
print(mat[0, 0])
print(mat[1, 1])
print("The element at 2,2 is: ", mat[2, 2])

[[  1   2   4]
 [ 89  23   0]
 [ 45  90 221]]
<class 'numpy.ndarray'>
1
23
The element at 2,2 is:  221


In [37]:
arr20 = np. array([0, 90, 80, 70, 60, 50, 40, 30, 20, 10])
print(arr20)
print(arr20.dtype)
print(arr20.itemsize)
print(arr20.ndim)
print(arr20.shape)
print(arr20.size)

[ 0 90 80 70 60 50 40 30 20 10]
int64
8
1
(10,)
10


In [38]:
# Slicing of array
print(arr20[:])
print(arr20[:5])
print(arr20[5:])
print(arr20[::2])
print(arr20[::-1])

[ 0 90 80 70 60 50 40 30 20 10]
[ 0 90 80 70 60]
[50 40 30 20 10]
[ 0 80 60 40 20]
[10 20 30 40 50 60 70 80 90  0]


In [39]:
#Slicing of 2D matrix
mat = np.array([[1, 2, 4],
               [89, 23, 0],
               [45 ,90, 221]])
print(mat)
print()
print(mat[0:2, 1:3])
print()
print(mat[:, 1])
print()
print(mat[2:7])
print(mat[2:7])

[[  1   2   4]
 [ 89  23   0]
 [ 45  90 221]]

[[ 2  4]
 [23  0]]

[ 2 23 90]

[[ 45  90 221]]
[[ 45  90 221]]


In [40]:
print(mat[1, :])

[89 23  0]


In [41]:
# updating the elements
arr21 = np.array([234, 789, 304, 345])
print(arr21)
arr21[0] = 5656
arr21[3] = 999
print("The updated array: ", arr21)

[234 789 304 345]
The updated array:  [5656  789  304  999]


In [42]:
# Udating the elements of 2d array
new_2darr = np.array([[12, 34], [67, 89]])
print(new_2darr)
new_2darr[1, 0] = 9090
new_2darr[0, 0] = 777
print(new_2darr)

[[12 34]
 [67 89]]
[[ 777   34]
 [9090   89]]


In [43]:
# Array operations
arr22 = np.array([90, 415 ,23 ,45])
print(arr22)
print(arr22 + 10)
print(arr22 - 10)
print(arr22 * 2)
print(arr22 ** 2)
print(arr22 // 2)
print(arr22 % 2)

[ 90 415  23  45]
[100 425  33  55]
[ 80 405  13  35]
[180 830  46  90]
[  8100 172225    529   2025]
[ 45 207  11  22]
[0 1 1 1]


In [44]:
# element wise operations
a = np.array([23, 12, 344, 55])
print(a)
b = np.array([68, 30, 1, 2])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)

[ 23  12 344  55]
[ 91  42 345  57]
[-45 -18 343  53]
[1564  360  344  110]
[3.38235294e-01 4.00000000e-01 3.44000000e+02 2.75000000e+01]
[  0   0 344  27]


In Python, numpy._core.fromnumeric is a sub-module of NumPy containing high-level, non-deprecated functions designed to operate on array-like objects

In [45]:
# Aggregation function
arr23 = np.array([11, 12 ,13 ,14,15])
print(arr23)
print(np.sum(arr23))
print(np.min(arr23))
print(np.max(arr23))
print(np.mean(arr23))
print(np.median(arr23))
print(np.std(arr23))
print(np.std(arr23))
print(np.var(arr23))
print(np.prod(arr23))

[11 12 13 14 15]
65
11
15
13.0
13.0
1.4142135623730951
1.4142135623730951
2.0
360360


In [46]:
# Searching
arr24 = np.array([67, 7,8 ,90, 8,9, 45 ,334])
print(arr24)
print(np.where(arr24 == 20))
print(np.where(arr24 > 30))

[ 67   7   8  90   8   9  45 334]
(array([], dtype=int64),)
(array([0, 3, 6, 7]),)


In [47]:
arr24 = np.array([67, 7, 8, 90, 8, 9, 45, 334])
print(arr24)

print(np.where(arr24 == 20))      # Returns empty tuple if not found
print(np.where(arr24 > 30))
print(np.where(arr24 == 8))       # Will return indices where 8 appears

[ 67   7   8  90   8   9  45 334]
(array([], dtype=int64),)
(array([0, 3, 6, 7]),)
(array([2, 4]),)


In [48]:
indices = np.where(arr24 > 50)
print(indices)
print(arr24[arr24 > 50])
print(20 in arr24)

(array([0, 3, 7]),)
[ 67  90 334]
False


In [49]:
# Sorting of array
arr25 = np.array([2, 14, 45, 6, 43, 23])
print(arr25)
print(np.sort(arr25))

[ 2 14 45  6 43 23]
[ 2  6 14 23 43 45]


In [50]:
# Sorting in reverse order
print(np.sort(arr25)[::-1])

[45 43 23 14  6  2]


In [51]:
arr26 = np.array([14, 67, 47, 37, 27, 17])
print(arr26)
print(np.sort(arr26))
print(np.sort(arr26)[::-1])

[14 67 47 37 27 17]
[14 17 27 37 47 67]
[67 47 37 27 17 14]


In [52]:
#Reshaping
print(arr26.reshape(2, 3))
print(arr26.reshape(3, 2))

[[14 67 47]
 [37 27 17]]
[[14 67]
 [47 37]
 [27 17]]


In [53]:
# Flattening
mat_new = np.array([1, 2], [3, 4])
print(mat_new.flatten())
print(mat_new.ravel())

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [ ]:
arr27 = np. array([11, 13 ,15, 17, 19])
print(np.append(arr27, 13))
print(np.append(arr27, 999))
print(np.append(arr27, 34))
print()
print(np.insert(arr27, 1, 99))
print(np.insert(arr27, 2, 88))

In [ ]:
# Appending and inserting
print(np.delete(arr27, 1))
print(np.delete(arr27, 2))
print(arr27)

In [ ]:
arr_new2 = np.array([1, 2, 3])

print(np.append(arr_new2, 4))
print(np.insert(arr_new2, 1, 99))

In [ ]:
a = np.array([2, 3, 4, 5])
b = np.array([5, 67, 33])
print(np.concatenate((a, b)))

In [ ]:
# print(np.vstack((a, b)))
# print(np.hstack((a, b)))

In [ ]:
arr28 = np.array([1, 2, 3, 4, 5])
print(arr28)
copy_arr = arr28.copy()
print(copy_arr)
view_arr = arr28.view()
print(view_arr)
print()

arr28[0] = 100
print(arr28)
print(copy_arr)
print(view_arr)

In [ ]:
# Boolean indexing
arr29 = np.array([14, 24, 34, 44, 54])
print(arr29)
print(arr29[arr29 > 35])
print(arr29[arr29 % 3 == 0])
print(arr29[arr29 % 2 == 0])
print(arr29[arr29 % 4 == 0])


In [ ]:
arr30 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 14, 24, 34, 44, 54])
for i in arr30:
    print(i)

In [ ]:
mat_new5 = np.array([[11, 21], [13, 14]])
print(mat_new5)

for row in mat_new5:
    for element in row:
        print(element)

print()
for x in np.nditer(mat_new5):
    print(x)

In [ ]:
# Matrix operation
A = np.array([[1, 14],[ 89, 90]])
B = np.array([[1, 14],[ 89, 90]])
print(A + B)
print(A - B)
print(A * B) # Element wise
print()
print(A @ B) # matrix multiplication
print(np.dot(A, B))

In [ ]:
# Transpose
A = np.array([[1, 4, 6, 78], [23, 4, 12, 1]])
print(A)

print(A.T)
print()
print(np.transpose(A))

In [ ]:
arr31 = np.array([25, 64, 100, 144])
print(arr31)
# Some mathematical funcxtion
print(np.sqrt(arr31))
print(np.exp(arr31))
print(np.log(arr31))
print(np.sin(arr31))
print(np.cos(arr31))

In [ ]:
print(np.random.rand(4))
print(np.random.randint(1, 10, size=5))
print(np.random.rand(3, 3))
print()
print(np.random.randn(3, 3))

In [ ]:
# Important numpy methods
arr32 = np.array([15, 22, 33, 61])
print(arr32)

print(arr32.argmax())
print(arr32.argmin())
print(arr32.argsort())
print(arr32.cumsum())
print(arr32.cumprod())
print(np.unique(arr32))

In [ ]:
arr33 =  np.array([[1, 2], [3, 4]])
print(arr33)

print(np.linalg.det(arr33))
print(np.linalg.inv(arr33))
print(np.linalg.eig(arr33))

In [ ]:
# Printing the matrix in vertical manner
def print_matrix_vertical(matrix):
    """
    print matrix column by column
    """
    n = len(matrix)
    for col in range(n):
        for row in range(n):
            print(matrix[row][col], end=" ")
        print()

matrix = [[23, 34, 45],
          [21, 34, 43],
          [20, 43, 32]]
print('The Given matrix: ')
print_matrix_vertical(matrix)
print()

print("The matrix in Vertical manner: ")
print_matrix_vertical(matrix)

In [ ]:
# Prefix Sum
arr_prefix = np.array([2, 5, 3, 15])
print(arr_prefix)
prefix = np.cumsum(arr_prefix)
print(prefix)

In [ ]:
# Frequency Count
arr_freq = np.array([2, 5, 3, 2, 3, 4, 15])
values, counts = np.unique(arr_freq, return_counts=True)
print(values)
print(counts)


In [ ]:
# Reversing the array
arr_rev = np.array([2, 5, 3, 15])
print(arr_rev[::-1])

In [ ]:
import numpy as np

# 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# 3x2 matrix
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print("Matrix A (2x3):")
print(A)
print("\nMatrix B (3x2):")
print(B)

# Matrix multiplication: (2x3) @ (3x2) = (2x2)
result = A @ B
print("\nA @ B (2x2):")
print(result)

# Same result with np.dot()
result2 = np.dot(A, B)
print("\nnp.dot(A, B):")
print(result2)

# Manual calculation verification
print("\nManual calculation:")
print(f"Position [0,0]: {A[0][0]*B[0][0] + A[0][1]*B[1][0] + A[0][2]*B[2][0]} = {A[0][0]*B[0][0] + A[0][1]*B[1][0] + A[0][2]*B[2][0]}")
print(f"Position [0,1]: {A[0][0]*B[0][1] + A[0][1]*B[1][1] + A[0][2]*B[2][1]}")
print(f"Position [1,0]: {A[1][0]*B[0][0] + A[1][1]*B[1][0] + A[1][2]*B[2][0]}")
print(f"Position [1,1]: {A[1][0]*B[0][1] + A[1][1]*B[1][1] + A[1][2]*B[2][1]}")