NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently.

In [2]:
# pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

from dsa.fundamentals.arrays_basic import ones

print(np.__version__)


2.4.4


In [10]:
"""Creating the array"""
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)
print(type(arr1))
print()
print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>

int64
1
(6,)
6


In [14]:
"""Creating the 2D array"""
arr2 = np.array([[1 ,3 ,4],[5 ,6, 8]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.shape)
print(arr2.shape)


[[1 3 4]
 [5 6 8]]
<class 'numpy.ndarray'>
2
(2, 3)
(2, 3)


In [21]:
"""Built in functions"""
zeros = np.zeros((3,3))
print(zeros)
print(type(zeros))
print()

ones = np.ones((3,3))
print(ones)
print(type(ones))
print()

full = np.full((2, 2), 7)
print(full)
print(type(full))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>

[[7 7]
 [7 7]]
<class 'numpy.ndarray'>


In [23]:
eye = np.empty((2, 2))
print(eye)
print(type(eye))

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.06810132e-306]]
<class 'numpy.ndarray'>


In [25]:
# Sequences
arange = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)
print(arange)
print(linspace)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [28]:
np.random.rand
rand = np.random.rand(2, 2)
print(rand)
print()

randint = np.random.randint(1, 10, size=(2, 2))
print(randint)

[[0.98870472 0.59823519]
 [0.5315877  0.69196432]]

[[6 2]
 [3 2]]


In [29]:
np.random.seed(42)  # For reproducibility

rand = np.random.rand(3, 2)        # Uniform [0,1)
randint = np.random.randint(0, 10, size=(2, 3))
normal = np.random.normal(loc=0, scale=1, size=(3,))

print(rand)
print(randint)
print(normal)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
[[7 4 3]
 [7 7 2]]
[-0.46947439  0.54256004 -0.46341769]


In [31]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)      # Number of dimensions
print(a.shape)     # Tuple of dimensions
print(a.size)      # Total elements
print(a.dtype)     # Data type
print(a.itemsize)  # Bytes per element
print(a.nbytes)    # Total bytes

2
(2, 3)
6
int64
8
48


In [32]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)

# Explicit conversion
arr_int = arr.astype(np.int32)
print(arr_int)

float32
[1 2 3]


In [33]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(a[0])        # First row
print(a[0, 2])     # Element at (0,2) -> 3
print(a[-1, -1])   # Last element -> 12

[1 2 3 4]
3
12


In [34]:
print(a[0:2, 1:3])   # Rows 0-1, columns 1-2
# [[2 3]
#  [6 7]]

print(a[:, 2])       # All rows, column 2
print(a[1, :])       # Row 1, all columns

[[2 3]
 [6 7]]
[ 3  7 11]
[5 6 7 8]
